# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class uiWert(object):
    def setupUi(self, Wert):
        Wert.setObjectName("Wert")
        Wert.resize(1620, 787)
        Wert.setLayoutDirection(QtCore.Qt.LeftToRight)
        Wert.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(Wert)
        self.centralwidget.setStyleSheet("background-color: #9fe870")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(20, 20, 20, 20)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.user_button = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.user_button.sizePolicy().hasHeightForWidth())
        self.user_button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.user_button.setFont(font)
        self.user_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.user_button.setMouseTracking(False)
        self.user_button.setStyleSheet("background-color: #1a3300;\n"
"border-color: rgb(159, 232, 112);\n"
"color : #9fe870;\n"
"border-radius: 8px;\n"
"border-radius: 10px;\n"
"font-size: 14px;\n"
"padding: 8px 16px;  ")
        self.user_button.setAutoDefault(True)
        self.user_button.setDefault(False)
        self.user_button.setFlat(False)
        self.user_button.setObjectName("user_button")
        self.horizontalLayout.addWidget(self.user_button)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setStyleSheet("color:#1A3300;\n"
"text-align: center;\n"
"\n"
"background-color:#1A3300;\n"
"border-radius: 10px;\n"
"\n"
"\n"
"\n"
"")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout_2.setContentsMargins(100, 25, 100, -1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.currency_tittle = QtWidgets.QLabel(self.page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.currency_tittle.sizePolicy().hasHeightForWidth())
        self.currency_tittle.setSizePolicy(sizePolicy)
        self.currency_tittle.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.currency_tittle.setFont(font)
        self.currency_tittle.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.currency_tittle.setStyleSheet("color:#1A3300;\n"
"text-align: center;\n"
"padding: 10px;\n"
"background-color: #9fe870;\n"
"border-radius: 10px;\n"
"border-bottom: 3px solid #ffffff;\n"
"border-right: 3px solid #ffffff;\n"
"\n"
"\n"
"")
        self.currency_tittle.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.currency_tittle.setObjectName("currency_tittle")
        self.verticalLayout_2.addWidget(self.currency_tittle)
        spacerItem1 = QtWidgets.QSpacerItem(580, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.moneda_label = QtWidgets.QLabel(self.page)
        self.moneda_label.setStyleSheet("color:#ffffff;fe\n"
"text-align: center;\n"
"padding: 10px;\n"
"\n"
"border: 2px solid #9fe870\n"
"")
        self.moneda_label.setObjectName("moneda_label")
        self.horizontalLayout_2.addWidget(self.moneda_label)
        self.monto_input = QtWidgets.QLineEdit(self.page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(120)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.monto_input.sizePolicy().hasHeightForWidth())
        self.monto_input.setSizePolicy(sizePolicy)
        self.monto_input.setMinimumSize(QtCore.QSize(120, 0))
        self.monto_input.setMaximumSize(QtCore.QSize(150, 16777215))
        self.monto_input.setStyleSheet("background-color: #ffffff;\n"
"border-radius: 8px;\n"
"border-color: #666666;\n"
"\n"
"")
        self.monto_input.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.monto_input.setObjectName("monto_input")
        self.horizontalLayout_2.addWidget(self.monto_input)
        self.moneda_combo_box = QtWidgets.QComboBox(self.page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.moneda_combo_box.sizePolicy().hasHeightForWidth())
        self.moneda_combo_box.setSizePolicy(sizePolicy)
        self.moneda_combo_box.setMinimumSize(QtCore.QSize(80, 0))
        self.moneda_combo_box.setMaximumSize(QtCore.QSize(120, 16777215))
        self.moneda_combo_box.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.moneda_combo_box.setStyleSheet("border: 2px solid #9fe870;\n"
"border-radius: 8px;\n"
"color: #9fe870;")
        self.moneda_combo_box.setObjectName("moneda_combo_box")
        self.horizontalLayout_2.addWidget(self.moneda_combo_box)
        self.convertir_button = QtWidgets.QPushButton(self.page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.convertir_button.sizePolicy().hasHeightForWidth())
        self.convertir_button.setSizePolicy(sizePolicy)
        self.convertir_button.setMaximumSize(QtCore.QSize(80, 16777215))
        self.convertir_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.convertir_button.setStyleSheet("background-color:#9fe870;\n"
"color:#1a3300;\n"
"border-radius: 8px;\n"
"text-decoration: underline;")
        self.convertir_button.setObjectName("convertir_button")
        self.horizontalLayout_2.addWidget(self.convertir_button)
        self.cambio_combo_box = QtWidgets.QComboBox(self.page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cambio_combo_box.sizePolicy().hasHeightForWidth())
        self.cambio_combo_box.setSizePolicy(sizePolicy)
        self.cambio_combo_box.setMinimumSize(QtCore.QSize(80, 0))
        self.cambio_combo_box.setMaximumSize(QtCore.QSize(120, 16777215))
        self.cambio_combo_box.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cambio_combo_box.setStyleSheet("border: 2px solid #9fe870;\n"
"border-radius: 8px;\n"
"color: #9fe870;")
        self.cambio_combo_box.setObjectName("cambio_combo_box")
        self.horizontalLayout_2.addWidget(self.cambio_combo_box)
        self.conversion_text = QtWidgets.QLineEdit(self.page)
        self.conversion_text.setStyleSheet("border-radius: 8px;\n"
"background-color: #f0f0f0;\n"
"")
        self.conversion_text.setText("")
        self.conversion_text.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.conversion_text.setReadOnly(True)
        self.conversion_text.setObjectName("conversion_text")
        self.horizontalLayout_2.addWidget(self.conversion_text)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.info_label = QtWidgets.QLabel(self.page)
        self.info_label.setStyleSheet("color: #9fe870;\n"
"")
        self.info_label.setAlignment(QtCore.Qt.AlignCenter)
        self.info_label.setObjectName("info_label")
        self.verticalLayout_2.addWidget(self.info_label)
        spacerItem4 = QtWidgets.QSpacerItem(17, 17, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem4)
        self.textEdit = QtWidgets.QTextEdit(self.page)
        self.textEdit.setMinimumSize(QtCore.QSize(0, 200))
        self.textEdit.setMaximumSize(QtCore.QSize(16777215, 250))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.textEdit.setFont(font)
        self.textEdit.setStyleSheet("background-color: #9fe870;\n"
"border-bottom: 3px solid #ffffff;\n"
"border-right: 3px solid #ffffff;")
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout_2.addWidget(self.textEdit)
        spacerItem5 = QtWidgets.QSpacerItem(17, 202, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem5)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.page_2)
        self.verticalLayout_3.setContentsMargins(100, 25, 100, -1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.economic_tittle = QtWidgets.QLabel(self.page_2)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.economic_tittle.setFont(font)
        self.economic_tittle.setStyleSheet("color:#1A3300;\n"
"text-align: center;\n"
"padding: 10px;\n"
"background-color: #9fe870;\n"
"border-radius: 10px;\n"
"border-bottom: 3px solid #ffffff;\n"
"border-right: 3px solid #ffffff;")
        self.economic_tittle.setAlignment(QtCore.Qt.AlignCenter)
        self.economic_tittle.setObjectName("economic_tittle")
        self.verticalLayout_3.addWidget(self.economic_tittle)
        spacerItem6 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_3.addItem(spacerItem6)
        self.datos_group = QtWidgets.QGroupBox(self.page_2)
        self.datos_group.setObjectName("datos_group")
        self.gridLayout = QtWidgets.QGridLayout(self.datos_group)
        self.gridLayout.setObjectName("gridLayout")
        self.pais_label = QtWidgets.QLabel(self.datos_group)
        self.pais_label.setStyleSheet("color:#ffffff;fe\n"
"text-align: center;\n"
"padding: 10px;\n"
"border: 2px solid #9fe870")
        self.pais_label.setObjectName("pais_label")
        self.gridLayout.addWidget(self.pais_label, 0, 1, 1, 1)
        self.indicador_label = QtWidgets.QLabel(self.datos_group)
        self.indicador_label.setStyleSheet("color:#ffffff;\n"
"text-align: start;\n"
"padding: 10px;\n"
"border: 2px solid #9fe870")
        self.indicador_label.setAlignment(QtCore.Qt.AlignCenter)
        self.indicador_label.setObjectName("indicador_label")
        self.gridLayout.addWidget(self.indicador_label, 0, 3, 1, 1)
        self.pais_combo = QtWidgets.QComboBox(self.datos_group)
        self.pais_combo.setMinimumSize(QtCore.QSize(180, 0))
        self.pais_combo.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pais_combo.setStyleSheet("border: 2px solid #9fe870;\n"
"border-radius: 8px;\n"
"color: #9fe870;")
        self.pais_combo.setObjectName("pais_combo")
        self.gridLayout.addWidget(self.pais_combo, 0, 2, 1, 1)
        self.indicador_combo = QtWidgets.QComboBox(self.datos_group)
        self.indicador_combo.setMinimumSize(QtCore.QSize(180, 0))
        self.indicador_combo.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.indicador_combo.setStyleSheet("border: 2px solid #9fe870;\n"
"border-radius: 8px;\n"
"color: #9fe870;")
        self.indicador_combo.setObjectName("indicador_combo")
        self.gridLayout.addWidget(self.indicador_combo, 0, 4, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem7, 0, 0, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem8, 0, 5, 1, 1)
        self.datos_button = QtWidgets.QPushButton(self.datos_group)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.datos_button.sizePolicy().hasHeightForWidth())
        self.datos_button.setSizePolicy(sizePolicy)
        self.datos_button.setMinimumSize(QtCore.QSize(0, 40))
        self.datos_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.datos_button.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.datos_button.setAutoFillBackground(False)
        self.datos_button.setStyleSheet("background-color:#9fe870;\n"
"color:#000000;\n"
"border-radius: 10px;\n"
"padding: 10px;\n"
"text-decoration: underline;\n"
"")
        self.datos_button.setObjectName("datos_button")
        self.gridLayout.addWidget(self.datos_button, 1, 3, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem9, 1, 4, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem10, 1, 2, 1, 1)
        self.verticalLayout_3.addWidget(self.datos_group)
        spacerItem11 = QtWidgets.QSpacerItem(20, 15, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_3.addItem(spacerItem11)
        self.datos_text = QtWidgets.QTextEdit(self.page_2)
        self.datos_text.setMinimumSize(QtCore.QSize(0, 300))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.datos_text.setFont(font)
        self.datos_text.setStyleSheet("background-color: #9fe870;\n"
"border-bottom: 3px solid #ffffff;\n"
"border-right: 3px solid #ffffff;")
        self.datos_text.setReadOnly(True)
        self.datos_text.setObjectName("datos_text")
        self.verticalLayout_3.addWidget(self.datos_text)
        spacerItem12 = QtWidgets.QSpacerItem(20, 100, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_3.addItem(spacerItem12)
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.page_3)
        self.verticalLayout_4.setContentsMargins(100, 25, 100, -1)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.notes_tittle = QtWidgets.QLabel(self.page_3)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.notes_tittle.setFont(font)
        self.notes_tittle.setStyleSheet("color:#1A3300;\n"
"text-align: center;\n"
"padding: 10px;\n"
"background-color: #9fe870;\n"
"border-radius: 10px;\n"
"border-bottom: 3px solid #ffffff;\n"
"border-right: 3px solid #ffffff;")
        self.notes_tittle.setAlignment(QtCore.Qt.AlignCenter)
        self.notes_tittle.setObjectName("notes_tittle")
        self.verticalLayout_4.addWidget(self.notes_tittle)
        spacerItem13 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_4.addItem(spacerItem13)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.nota_label = QtWidgets.QLabel(self.page_3)
        self.nota_label.setStyleSheet("color:#ffffff;\n"
"text-align: center;\n"
"padding: 10px;\n"
"border: 2px solid #9fe870")
        self.nota_label.setObjectName("nota_label")
        self.horizontalLayout_4.addWidget(self.nota_label)
        self.notas_combo = QtWidgets.QComboBox(self.page_3)
        self.notas_combo.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.notas_combo.setStyleSheet("border: 2px solid #9fe870;\n"
"border-radius: 8px;\n"
"color: #9fe870;")
        self.notas_combo.setObjectName("notas_combo")
        self.horizontalLayout_4.addWidget(self.notas_combo)
        self.cargar_nota_button = QtWidgets.QPushButton(self.page_3)
        self.cargar_nota_button.setMinimumSize(QtCore.QSize(100, 35))
        self.cargar_nota_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cargar_nota_button.setStyleSheet("background-color:#9fe870;\n"
"color:#000000;\n"
"border-radius: 10px;\n"
"text-decoration: underline;")
        self.cargar_nota_button.setObjectName("cargar_nota_button")
        self.horizontalLayout_4.addWidget(self.cargar_nota_button)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem14)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.titulo_nota_input = QtWidgets.QLineEdit(self.page_3)
        self.titulo_nota_input.setStyleSheet("background-color: #9fe870;\n"
"border-bottom: 3px solid #ffffff;\n"
"border-right: 3px solid #ffffff;")
        self.titulo_nota_input.setObjectName("titulo_nota_input")
        self.horizontalLayout_3.addWidget(self.titulo_nota_input)
        self.nueva_button = QtWidgets.QPushButton(self.page_3)
        self.nueva_button.setMinimumSize(QtCore.QSize(100, 35))
        self.nueva_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.nueva_button.setStyleSheet("background-color:#9fe870;\n"
"color:#000000;\n"
"border-radius: 10px;\n"
"text-decoration: underline;")
        self.nueva_button.setObjectName("nueva_button")
        self.horizontalLayout_3.addWidget(self.nueva_button)
        self.guardar_button = QtWidgets.QPushButton(self.page_3)
        self.guardar_button.setMinimumSize(QtCore.QSize(100, 35))
        self.guardar_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.guardar_button.setStyleSheet("background-color:#9fe870;\n"
"color:#000000;\n"
"border-radius: 10px;\n"
"text-decoration: underline;")
        self.guardar_button.setObjectName("guardar_button")
        self.horizontalLayout_3.addWidget(self.guardar_button)
        self.eliminar_button = QtWidgets.QPushButton(self.page_3)
        self.eliminar_button.setMinimumSize(QtCore.QSize(100, 35))
        self.eliminar_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.eliminar_button.setStyleSheet("background-color:#9fe870;\n"
"color:#000000;\n"
"border-radius: 10px;\n"
"text-decoration: underline;")
        self.eliminar_button.setObjectName("eliminar_button")
        self.horizontalLayout_3.addWidget(self.eliminar_button)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem15)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        spacerItem16 = QtWidgets.QSpacerItem(20, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_4.addItem(spacerItem16)
        self.nota_input = QtWidgets.QTextEdit(self.page_3)
        self.nota_input.setMinimumSize(QtCore.QSize(0, 300))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.nota_input.setFont(font)
        self.nota_input.setStyleSheet("background-color: #9fe870;\n"
"border-bottom: 3px solid #ffffff;\n"
"border-right: 3px solid #ffffff;")
        self.nota_input.setObjectName("nota_input")
        self.verticalLayout_4.addWidget(self.nota_input)
        spacerItem17 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_4.addItem(spacerItem17)
        self.stackedWidget.addWidget(self.page_3)
        self.verticalLayout.addWidget(self.stackedWidget)
        Wert.setCentralWidget(self.centralwidget)
        self.menu_bar = QtWidgets.QMenuBar(Wert)
        self.menu_bar.setGeometry(QtCore.QRect(0, 0, 1620, 26))
        self.menu_bar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.menu_bar.setAutoFillBackground(False)
        self.menu_bar.setStyleSheet("background-color: #1A3300;\n"
"color: #9FE870;\n"
"\n"
"        ")
        self.menu_bar.setDefaultUp(False)
        self.menu_bar.setNativeMenuBar(True)
        self.menu_bar.setObjectName("menu_bar")
        self.menu_change = QtWidgets.QMenu(self.menu_bar)
        self.menu_change.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.menu_change.setObjectName("menu_change")
        self.menuEconomic_Data = QtWidgets.QMenu(self.menu_bar)
        self.menuEconomic_Data.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.menuEconomic_Data.setObjectName("menuEconomic_Data")
        self.menuNotes = QtWidgets.QMenu(self.menu_bar)
        self.menuNotes.setGeometry(QtCore.QRect(620, 202, 159, 78))
        self.menuNotes.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.menuNotes.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.menuNotes.setObjectName("menuNotes")
        Wert.setMenuBar(self.menu_bar)
        self.action_view_rates_action = QtWidgets.QAction(Wert)
        self.action_view_rates_action.setObjectName("action_view_rates_action")
        self.action_view_data = QtWidgets.QAction(Wert)
        self.action_view_data.setObjectName("action_view_data")
        self.action_view_countries = QtWidgets.QAction(Wert)
        self.action_view_countries.setObjectName("action_view_countries")
        self.action_view_notes = QtWidgets.QAction(Wert)
        self.action_view_notes.setObjectName("action_view_notes")
        self.action_about_change = QtWidgets.QAction(Wert)
        self.action_about_change.setObjectName("action_about_change")
        self.action_about_eco = QtWidgets.QAction(Wert)
        self.action_about_eco.setObjectName("action_about_eco")
        self.action_about_notes = QtWidgets.QAction(Wert)
        self.action_about_notes.setObjectName("action_about_notes")
        self.menu_change.addAction(self.action_view_rates_action)
        self.menuEconomic_Data.addAction(self.action_view_data)
        self.menuNotes.addAction(self.action_view_notes)
        self.menu_bar.addAction(self.menu_change.menuAction())
        self.menu_bar.addAction(self.menuEconomic_Data.menuAction())
        self.menu_bar.addAction(self.menuNotes.menuAction())

        self.retranslateUi(Wert)
        self.stackedWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(Wert)

    def retranslateUi(self, Wert):
        _translate = QtCore.QCoreApplication.translate
        Wert.setWindowTitle(_translate("Wert", "Wert"))
        self.user_button.setText(_translate("Wert", "👤"))
        self.currency_tittle.setText(_translate("Wert", "Conversor de Monedas"))
        self.moneda_label.setText(_translate("Wert", "Cantidad"))
        self.monto_input.setPlaceholderText(_translate("Wert", "100.00"))
        self.convertir_button.setText(_translate("Wert", "-->"))
        self.conversion_text.setPlaceholderText(_translate("Wert", "0.00"))
        self.info_label.setText(_translate("Wert", "Consulta tasas de cambio en tiempo real con Wert. Obtene valores actualizados de mas X monedas, incluyendo USD, EUR, ARS y más. Conversiones precisas basadas en el mercado forex para tus operaciones internacionales."))
        self.textEdit.setPlaceholderText(_translate("Wert", "Más detalles sobre la conversión aparecerán aquí..."))
        self.economic_tittle.setText(_translate("Wert", "Datos Economicos por País"))
        self.datos_group.setTitle(_translate("Wert", "Seleccione los datos"))
        self.pais_label.setText(_translate("Wert", "País:"))
        self.indicador_label.setText(_translate("Wert", "Indicador:"))
        self.datos_button.setText(_translate("Wert", "Obtener datos del País"))
        self.datos_text.setPlaceholderText(_translate("Wert", "Seleccione un país e indicador para mostrar datos..."))
        self.notes_tittle.setText(_translate("Wert", "Mis notas"))
        self.nota_label.setText(_translate("Wert", "Nota:"))
        self.cargar_nota_button.setText(_translate("Wert", "Cargar"))
        self.titulo_nota_input.setPlaceholderText(_translate("Wert", "Titulo de la nota..."))
        self.nueva_button.setText(_translate("Wert", "Nueva"))
        self.guardar_button.setText(_translate("Wert", "Guardar"))
        self.eliminar_button.setText(_translate("Wert", "Eliminar"))
        self.nota_input.setPlaceholderText(_translate("Wert", "Escribe tu nota aquí..."))
        self.menu_change.setTitle(_translate("Wert", "Change"))
        self.menuEconomic_Data.setTitle(_translate("Wert", "Economic Data"))
        self.menuNotes.setTitle(_translate("Wert", "Notes"))
        self.action_view_rates_action.setText(_translate("Wert", "View rates"))
        self.action_view_data.setText(_translate("Wert", "View countries data"))
        self.action_view_countries.setText(_translate("Wert", "View countries"))
        self.action_view_notes.setText(_translate("Wert", "View notes"))
        self.action_about_change.setText(_translate("Wert", "About"))
        self.action_about_eco.setText(_translate("Wert", "About"))
        self.action_about_notes.setText(_translate("Wert", "About"))
